### ISSUE TITLE
Making it work with Statamic 2.11.10

### ISSUE THREAD

**Issue by bluetidepro** [mattias-persson/statamic-translation-manager#1]
On https://statamic.com/marketplace/addons/translation-manager you mentioned:

>  "This  plugin has known issues with the latest versions of Statamic. If you're able to chip in to make it compatible, we'd be very thankful! Submit a PR on Github or email me at mattias@happypixels.se. Thanks!" 

I was curious if you had more specific details on what is broken and needs help being fixed to work on the current Statamic 2.11.10 version. Our team would love to be able to use this plugin, and could possibly help contribute to make it compatible.

**Comment by mattias-sanfridsson** [comment]
@bluetidepro I'm afraid I'm not sure about the details, but I believe it crashes on newer versions of Statamic. I also think a full lookover would be good to make sure it supports any new field types. Would be awesome if you have time to take a look at it, I'll also try to make time for it as I've seen a bit of interest in this plugin.

**Comment by mattias-sanfridsson** [comment]
@bluetidepro I have now released v2.0 of the addon, with support for Statamic 2.11. Feel free to test it out and please let me know if you encounter any issues!

**Comment by bluetidepro** [comment]
@mattias-persson Awesome! Thanks for your work on this. Will get it in our site and start testing ASAP.
