### ISSUE TITLE
Slug isn't exported for translation

### ISSUE THREAD

**Issue by aryehraber** [mattias-persson/statamic-translation-manager#10]
Noticed today that a page's `slug` doesn't get exported (same for entries, etc), even while the `localizable` option is set:

```
slug:
  type: text
  localizable: true
```

I noticed that Statamic actually _always_ allows slugs to be translated, even if the above is missing or set to `false`. I feel that _always_ adding isn't necessarily what users want, so I think it should only get exported if the above config is added to the fieldset.

I've just got this working locally, so can push a PR if interested!

**Comment by mattias-sanfridsson** [comment]
Ah, nice! I think I may have just expected slugs to not be translatable... I'd appreciate a PR! Thanks for your continued efforts to improve this addon ❤️
