### ISSUE TITLE
Change default selection to "No" when using "Select what to export"

### ISSUE THREAD

**Issue by aryehraber** [mattias-persson/statamic-translation-manager#6]
When using the "Select what to export" option, I tend to only select a particular page or collection, etc. meaning I need to set all other select dropdowns to "No" before being able to click "Export". 

I feel it would be better to set everything to "No" by default and allow the user to opt-in for the content they want to export. Especially since there's already an "Export everything" option.

Happy to submit a PR for this, just wanted to check if this idea aligns with you.

**Comment by mattias-sanfridsson** [comment]
That's a very good point, this has bothered me before as well. I'd love a PR for it!

**Comment by aryehraber** [comment]
Awesome, already changed it locally so will submit a PR shortly 👍
